// old/packages/react/src/index.tsx
"use client";

import { useEffect, useRef, type RefObject } from "react";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "../../main/src/motionrail";

export interface MotionRailProps extends React.HTMLAttributes<HTMLDivElement> {
  ref?: RefObject<MotionRailClass>;
  divRef?: RefObject<HTMLDivElement>;
  options?: MotionRailOptions;
}

function MotionRailReact({ options, ref, divRef, ...divProps }: MotionRailProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const motionRailRef = useRef<MotionRailClass | null>(null);
  const { children, ...restDivProps } = divProps || {};

  useEffect(() => {
    if (!containerRef.current) return;

    motionRailRef.current = new MotionRailClass(
      containerRef.current,
      options || {},
    );
    if (ref) {
      ref.current = motionRailRef.current;
    }

    if (divRef) {
      divRef.current = containerRef.current;
    }

    return () => {
      if (motionRailRef.current) {
        motionRailRef.current.destroy();
        motionRailRef.current = null;
      }
    };
  }, [options]);

  useEffect(() => {
    if (motionRailRef.current) {
      motionRailRef.current.update();
    }
  }, [children]);

  return (
    <div ref={containerRef} data-motionrail {...restDivProps}>
      <div data-motionrail-scrollable>
        <div data-motionrail-grid>{children}</div>
      </div>
    </div>
  );
}

export { MotionRailReact as MotionRail };

// old/packages/solid/src/index.tsx
/** @jsxImportSource solid-js */
import {
  onMount,
  onCleanup,
  createEffect,
  type JSX,
  splitProps,
} from "solid-js";
import { isServer } from "solid-js/web";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "../../main/src/motionrail";

export interface MotionRailProps
  extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "ref"> {
  ref?: (instance: MotionRailClass) => void;
  divRef?: (element: HTMLDivElement) => void;
  options?: MotionRailOptions;
}

function MotionRailSolid(props: MotionRailProps) {
  const [local, others] = splitProps(props, [
    "options",
    "ref",
    "divRef",
    "children",
  ]);

  if (isServer) {
    return <div {...others}>{local.children}</div>;
  }

  let containerRef: HTMLDivElement | undefined;
  let motionRailInstance: MotionRailClass | null = null;

  onMount(() => {
    if (!containerRef) return;

    motionRailInstance = new MotionRailClass(containerRef, local.options || {});

    if (local.ref) {
      local.ref(motionRailInstance);
    }

    if (local.divRef) {
      local.divRef(containerRef);
    }
  });

  createEffect(() => {
    // Track children changes
    // @ts-ignore - intentionally unused to track reactivity
    const _ = local.children;

    if (motionRailInstance) {
      motionRailInstance.update();
    }
  });

  onCleanup(() => {
    if (motionRailInstance) {
      motionRailInstance.destroy();
      motionRailInstance = null;
    }
  });

  return (
    <div ref={containerRef} data-motionrail {...others}>
      <div data-motionrail-scrollable>
        <div data-motionrail-grid>{local.children}</div>
      </div>
    </div>
  );
}

export { MotionRailSolid as MotionRail };
