// frameworks/solid/src/lib/main.tsx
import { onMount, onCleanup, createEffect, children as resolveChildren, type JSX } from "solid-js";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps extends JSX.HTMLAttributes<HTMLDivElement> {
  options?: MotionRailOptions;
  children?: JSX.Element;
}

function MotionRailSolid(props: MotionRailProps) {
  let containerRef: HTMLDivElement | undefined;
  let motionRailInstance: MotionRailClass | null = null;
  const resolved = resolveChildren(() => props.children);

  onMount(() => {
    if (!containerRef) return;

    motionRailInstance = new MotionRailClass(
      containerRef,
      props.options || {},
    );
  });

  createEffect(() => {
    // React to children changes
    resolved();
    if (motionRailInstance) {
      motionRailInstance.update();
    }
  });

  onCleanup(() => {
    if (motionRailInstance) {
      motionRailInstance.destroy();
      motionRailInstance = null;
    }
  });

  return (
    <div ref={containerRef} data-motionrail {...props}>
      <div data-motionrail-scrollable>
        <div data-motionrail-grid>{resolved()}</div>
      </div>
    </div>
  );
}

export { MotionRailSolid as MotionRail };

// frameworks/preact/src/lib/main.tsx
import { useEffect, useRef } from "preact/hooks";
import type { JSX } from "preact";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
  options?: MotionRailOptions;
}

function MotionRailPreact({ options, ...divProps }: MotionRailProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const motionRailRef = useRef<MotionRailClass | null>(null);
  const { children, ...restDivProps } = divProps || {};

  useEffect(() => {
    if (!containerRef.current) return;

    motionRailRef.current = new MotionRailClass(
      containerRef.current,
      options || {},
    );

    return () => {
      if (motionRailRef.current) {
        motionRailRef.current.destroy();
        motionRailRef.current = null;
      }
    };
  }, [options]);

  useEffect(() => {
    if (motionRailRef.current) {
      motionRailRef.current.update();
    }
  }, [children]);

  return (
    <div ref={containerRef} data-motionrail {...restDivProps}>
      <div data-motionrail-scrollable>
        <div data-motionrail-grid>{children}</div>
      </div>
    </div>
  );
}

export { MotionRailPreact as MotionRail };
