// frameworks/solid/src/index.tsx
import { onMount, onCleanup, createEffect, children as resolveChildren, type JSX } from 'solid-js'
import { MotionRail as MotionRailClass, type MotionRailOptions } from 'motionrail'

export interface MotionRailProps extends JSX.HTMLAttributes<HTMLDivElement> {
  options?: MotionRailOptions
  children?: JSX.Element
}

function MotionRailSolid(props: MotionRailProps) {
  let containerRef: HTMLDivElement | undefined
  let motionRailInstance: MotionRailClass | null = null
  const resolved = resolveChildren(() => props.children)

  onMount(() => {
    if (!containerRef) return

    motionRailInstance = new MotionRailClass(containerRef, props.options || {})
  })

  createEffect(() => {
    // React to children changes
    resolved()
    if (motionRailInstance) {
      motionRailInstance.update()
    }
  })

  onCleanup(() => {
    if (motionRailInstance) {
      motionRailInstance.destroy()
      motionRailInstance = null
    }
  })

  // Extract options and rest props
  const { options, children, ...restProps } = props
  // Compute style for scrollable div
  const scrollableStyle = options?.containerName
    ? { containerName: options.containerName }
    : undefined
  return (
    <div ref={containerRef} data-motionrail {...restProps}>
      <div data-motionrail-scrollable style={scrollableStyle}>
        <div data-motionrail-grid>{resolved()}</div>
      </div>
    </div>
  )
}

export { MotionRailSolid as MotionRail }

// frameworks/react/src/main.tsx
"use client";

import { useEffect, useRef, type MutableRefObject } from "react";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps extends React.HTMLAttributes<HTMLDivElement> {
  ref?: MutableRefObject<MotionRailClass | null>;
  divRef?: MutableRefObject<HTMLDivElement | null>;
  options?: MotionRailOptions;
}

function MotionRailReact({
  options,
  ref,
  divRef,
  ...divProps
}: MotionRailProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const motionRailRef = useRef<MotionRailClass | null>(null);
  const { children, ...restDivProps } = divProps || {};

  useEffect(() => {
    if (!containerRef.current) return;

    motionRailRef.current = new MotionRailClass(
      containerRef.current,
      options || {},
    );
    if (ref) {
      ref.current = motionRailRef.current;
    }

    if (divRef) {
      divRef.current = containerRef.current;
    }

    return () => {
      if (motionRailRef.current) {
        motionRailRef.current.destroy();
        motionRailRef.current = null;
      }
    };
  }, [options]);

  useEffect(() => {
    if (motionRailRef.current) {
      motionRailRef.current.update();
    }
  }, [children]);

  return (
    <>
      <div ref={containerRef} data-motionrail {...restDivProps}>
        <div
          data-motionrail-scrollable
          style={{ containerName: options?.containerName }}
        >
          <div data-motionrail-grid>{children}</div>
        </div>
      </div>
    </>
  );
}

export { MotionRailReact as MotionRail };
