// frameworks/react/src/main.tsx
"use client";

import { useEffect, useRef, type MutableRefObject } from "react";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps extends React.HTMLAttributes<HTMLDivElement> {
  ref?: MutableRefObject<MotionRailClass | null>;
  divRef?: MutableRefObject<HTMLDivElement | null>;
  options?: MotionRailOptions;
}

function MotionRailReact({
  options,
  ref,
  divRef,
  ...divProps
}: MotionRailProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const motionRailRef = useRef<MotionRailClass | null>(null);
  const { children, ...restDivProps } = divProps || {};

  useEffect(() => {
    if (!containerRef.current) return;

    motionRailRef.current = new MotionRailClass(
      containerRef.current,
      options || {},
    );
    if (ref) {
      ref.current = motionRailRef.current;
    }

    if (divRef) {
      divRef.current = containerRef.current;
    }

    return () => {
      if (motionRailRef.current) {
        motionRailRef.current.destroy();
        motionRailRef.current = null;
      }
    };
  }, [options]);

  useEffect(() => {
    if (motionRailRef.current) {
      motionRailRef.current.update();
    }
  }, [children]);

  return (
    <>
      <div ref={containerRef} data-motionrail {...restDivProps}>
        <div
          data-motionrail-scrollable
          style={{ containerName: options?.containerName }}
        >
          <div data-motionrail-grid>{children}</div>
        </div>
      </div>
    </>
  );
}

export { MotionRailReact as MotionRail };

// frameworks/qwik/src/main.tsx
import { component$, useVisibleTask$, useSignal, Slot, noSerialize } from "@builder.io/qwik";
import type { QRL, QwikIntrinsicElements } from "@builder.io/qwik";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps {
  options?: MotionRailOptions
}

export const MotionRail = component$<MotionRailProps & QwikIntrinsicElements['div']>((props) => {


  const { options, ...divProps } = props;
  if(options && options.onChange) options.onChange = noSerialize(options.onChange as QRL<(state: any) => void>);

  const containerRef = useSignal<HTMLDivElement>();
  const motionRailRef = useSignal<MotionRailClass | null>(null);

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    if (!containerRef.value) return;

    motionRailRef.value = new MotionRailClass(
      containerRef.value,
      options || {}
    );

    cleanup(() => {
      if (motionRailRef.value) {
        motionRailRef.value.destroy();
        motionRailRef.value = null;
      }
    });
  });

  // Compute style for scrollable div
  const scrollableStyle = options?.containerName ? { containerName: options.containerName } : undefined;
  return (
    <div ref={containerRef} data-motionrail {...divProps}>
      <div data-motionrail-scrollable style={scrollableStyle}>
        <div data-motionrail-grid>
          <Slot />
        </div>
      </div>
    </div>
  );
});
