// frameworks/lit/src/lib/main.ts
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from 'motionrail';

@customElement('motionrail-element')
export class MotionRail extends LitElement {
  @property({ type: Object }) options: MotionRailOptions = {};
  
  private motionRailInstance: MotionRailClass | null = null;
  private containerRef: HTMLDivElement | null = null;

  firstUpdated() {
    this.containerRef = this.shadowRoot?.querySelector('[data-motionrail]') as HTMLDivElement;
    
    if (this.containerRef) {
      this.motionRailInstance = new MotionRailClass(
        this.containerRef,
        this.options
      );
    }
  }

  updated(changedProperties: Map<string, any>) {
    if (changedProperties.has('options') && this.motionRailInstance) {
      this.motionRailInstance.destroy();
      if (this.containerRef) {
        this.motionRailInstance = new MotionRailClass(
          this.containerRef,
          this.options
        );
      }
    }
  }

  disconnectedCallback() {
    super.disconnectedCallback();
    if (this.motionRailInstance) {
      this.motionRailInstance.destroy();
      this.motionRailInstance = null;
    }
  }

  render() {
    return html`
      <div data-motionrail>
        <div data-motionrail-scrollable>
          <div data-motionrail-grid>
            <slot></slot>
          </div>
        </div>
      </div>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'motionrail-element': MotionRail;
  }
}

// frameworks/solid/src/lib/main.tsx
import { onMount, onCleanup, createEffect, children as resolveChildren, type JSX } from "solid-js";
import {
  MotionRail as MotionRailClass,
  type MotionRailOptions,
} from "motionrail";

export interface MotionRailProps extends JSX.HTMLAttributes<HTMLDivElement> {
  options?: MotionRailOptions;
  children?: JSX.Element;
}

function MotionRailSolid(props: MotionRailProps) {
  let containerRef: HTMLDivElement | undefined;
  let motionRailInstance: MotionRailClass | null = null;
  const resolved = resolveChildren(() => props.children);

  onMount(() => {
    if (!containerRef) return;

    motionRailInstance = new MotionRailClass(
      containerRef,
      props.options || {},
    );
  });

  createEffect(() => {
    // React to children changes
    resolved();
    if (motionRailInstance) {
      motionRailInstance.update();
    }
  });

  onCleanup(() => {
    if (motionRailInstance) {
      motionRailInstance.destroy();
      motionRailInstance = null;
    }
  });

  return (
    <div ref={containerRef} data-motionrail {...props}>
      <div data-motionrail-scrollable>
        <div data-motionrail-grid>{resolved()}</div>
      </div>
    </div>
  );
}

export { MotionRailSolid as MotionRail };
